Repository SyntaxSentinels/SyntaxSentinels, pull requests merged in 2024-10, with the labels that each got.

#58 chore: Add makefile to SRS-Volere
  docs/SRS-Volere/Makefile
Labels: chore

#57 feat: Add Off-the-Shelf Solutions for SRS document
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#59 feat: Change license from MIT to GPLv3
  LICENSE
  docs/DevelopmentPlan/DevelopmentPlan.pdf
  docs/DevelopmentPlan/DevelopmentPlan.tex
Labels: documentation, feature

#53 performance requirements done
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#63 fix: Change data retention policy to "zero data retention"
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation, chore

#65 feat: Stated User Business (Cases) and Project Goals
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#64 feat: maintenance, supportability, and adaptability requirements
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#75 feat: Add new problems for SRS document
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#72 feat: Add security requirements
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#70 feat: User documentation and req
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#81 feat: Add Operational and Environmental Requirements for SRS
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#82 fix: User Business section corrected to intended definition of template
  docs/SRS-Volere/SRS.tex
Labels: documentation

#88 fix: Change in FRs to fully accommodate main success scenario
  docs/SRS-Volere/SRS.tex
Labels: documentation

#86 feat: add reflection part
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation

#91 fix: Some final edits for the reflection
  docs/SRS-Volere/SRS.tex
Labels: documentation

#118 feat: Add Safety and Security Requirements for Hazard Analysis
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#115 feat: SS-96 Initial draft of system boundaries
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
  docs/HazardAnalysis/assets/Component_Border.drawio
  docs/HazardAnalysis/assets/Component_Border.png
  docs/SRS-Volere/SRS.tex
Labels: documentation

#124 feat: 101 - Hazard Analysis Reflection
  docs/HazardAnalysis/HazardAnalysis.pdf
  docs/HazardAnalysis/HazardAnalysis.tex
Labels: documentation

#160 feat: add in all subsections of the general section
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
Labels: documentation

#164 fix: Fix traceability labels for requirements
  docs/SRS-Volere/SRS.pdf
  docs/SRS-Volere/SRS.tex
Labels: documentation, chore
