Repository SyntaxSentinels/SyntaxSentinels, pull requests merged in 2025-01, with the labels that each got.

#261 Initial MG document
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
  docs/DevelopmentPlan/DevelopmentPlan.pdf
Labels: documentation, feature

#279 Feat/ss 231 Module connection to Requirements
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#277 Feat/ss 233 Traceability from Modules to Requirements
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#276 Feat/ss 232 Initial Module Decomposition
  docs/Design/SoftArchitecture/MG.tex
Labels: documentation

#286 fix/SS-231 - fixed hierarchy for behaviour-hiding and software decision modules
  docs/Design/SoftArchitecture/MG.tex
Labels: chore

#287 fix/SS-239 - fixed module decomposition table in MIS
  docs/Design/SoftDetailedDes/MIS.tex
Labels: chore

#291 Fix/module guide formatting
  docs/Design/SoftArchitecture/MG.pdf
  docs/Design/SoftArchitecture/MG.tex
Labels: chore
